#!/usr/bin/env node

// Self-executing script to generate variables.json and variables.tsp from env/.env.{environment}
(async function main() {
  const fs = require("fs");
  const path = require("path");

  try {
    const envArg = process.argv[2] || "dev";

    // src/agent is the parent of this scripts directory
    const repoAgentDir = path.resolve(__dirname, "..");
    const envDir = path.join(repoAgentDir, "env");
    const forbiddenEnvFiles = [
      path.join(envDir, ".env.dev.user"),
      path.join(envDir, ".env.local"),
    ].filter((p) => fs.existsSync(p));
    if (forbiddenEnvFiles.length > 0) {
      console.error("Forbidden env files detected. Use env/.env.dev only.");
      console.error(`Delete these files: ${forbiddenEnvFiles.join(", ")}`);
      process.exitCode = 2;
      return;
    }
    const candidateEnvFiles = [path.join(envDir, `.env.${envArg}`)];
    const outTspPath = path.join(repoAgentDir, "src/agent/env.tsp");

    const existingEnvFiles = candidateEnvFiles.filter((p) => fs.existsSync(p));

    if (existingEnvFiles.length === 0) {
      console.error(
        `Environment files not found. Looked for: ${candidateEnvFiles.join(", ")}`
      );
      console.error(
        `Usage: node generate-env.js <environment>  (e.g. dev, prod). At least one env file is required.`
      );
      process.exitCode = 2;
      return;
    }

    const vars = {};

    // Merge env files in order; later files override earlier files.
    for (const envFilePath of existingEnvFiles) {
      const raw = fs.readFileSync(envFilePath, "utf8");

      for (const rawLine of raw.split(/\r?\n/)) {
        const line = rawLine.trim();
        if (!line || line.startsWith("#")) continue;

        // support lines like KEY=value or export KEY=value
        const cleaned = line.replace(/^export\s+/, "");
        const match = cleaned.match(/^([A-Za-z0-9_.-]+)\s*=\s*(.*)$/);
        if (!match) continue;

        const key = match[1];
        let value = match[2] || "";

        // strip surrounding single or double quotes
        if (
          (value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))
        ) {
          value = value.slice(1, -1);
        }

        // Unescape common sequences (keep as-is if not needed)
        value = value.replace(/\\n/g, "\n").replace(/\\r/g, "\r");

        vars[key] = value;
      }
    }

    // Backward-compatibility and compile-stability defaults for required TypeSpec env constants.
    if (!vars.PA_APP_SERVER_URL && vars.PA_SERVER_URL) {
      vars.PA_APP_SERVER_URL = vars.PA_SERVER_URL;
    }

    if (!vars.PA_APP_INVOKE_PATH) {
      vars.PA_APP_INVOKE_PATH = "/send-to-flow";
    }

    if (!vars.PA_APP_SERVER_URL) {
      vars.PA_APP_SERVER_URL = "http://localhost:3001";
    }

    if (!Object.prototype.hasOwnProperty.call(vars, "RELAY_SECRET")) {
      vars.RELAY_SECRET = "";
    }

    const tspLines = [];
    tspLines.push("// Auto-generated by scripts/generate-env.js - DO NOT EDIT");
    const sourceComment = existingEnvFiles
      .map((p) => path.relative(repoAgentDir, p).replace(/\\/g, "/"))
      .join(", ");
    tspLines.push(`// Source(s): ${sourceComment}`);
    tspLines.push("");
    tspLines.push("namespace Environment {");

    const keys = Object.keys(vars).sort();
    for (const originalKey of keys) {
      const value = vars[originalKey];

      // Convert original env key to a safe TypeSpec identifier: replace invalid chars with _ and ensure it doesn't start with a digit
      let ident = originalKey.replace(/[^A-Za-z0-9_]/g, "_");
      if (/^[0-9]/.test(ident)) ident = "_" + ident;

      // Add a comment with the original env key for traceability
      tspLines.push(`  // ${originalKey}`);

      // Escape backslashes and double quotes for safe TS string literal
      const escaped = value.replace(/\\/g, "\\\\").replace(/\"/g, '\\"');

      tspLines.push(`  const ${ident} = "${escaped}";`);
      tspLines.push("");
    }

    tspLines.push("}");

    fs.writeFileSync(outTspPath, tspLines.join("\n") + "\n", "utf8");

    console.log(`Generated: ${outTspPath}`);
  } catch (err) {
    console.error("Failed to generate environment variables:", err && err.stack ? err.stack : err);
    process.exitCode = 1;
  }
})();
